apiVersion: v1
kind: Service
metadata:
  name: demo-dc1-stargate-lb  # Unique name to avoid conflicts
  namespace: k8ssandra-operator
  annotations:
    metallb.universe.tf/loadBalancerIP: "192.168.64.104"  # Pick an IP from your pool
spec:
  selector:
    app.kubernetes.io/component: stargate  # Matches the Stargate deployment labels
    k8ssandra.io/stargate: demo-dc1-stargate  # Adjust based on your Stargate pod labels
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
    name: swagger-ui  # REST API + Swagger UI
  - protocol: TCP
    port: 8081
    targetPort: 8081
    name: auth  # Authorization endpoint
  type: LoadBalancer
  loadBalancerIP: "192.168.64.104"  # Fixed IP for Stargate Swagger UI