apiVersion: v1
kind: Pod
metadata:
  name: reaper-test
  namespace: k8ssandra-operator
spec:
  initContainers:
  - name: copy-config
    image: busybox
    command: ["sh", "-c", "cp /tmp/config/cassandra-reaper.yml /etc/cassandra-reaper/config/cassandra-reaper.yml"]
    volumeMounts:
    - name: config
      mountPath: /tmp/config
    - name: config-dir
      mountPath: /etc/cassandra-reaper/config
  containers:
  - name: reaper
    image: docker.io/thelastpickle/cassandra-reaper:3.8.0
    ports:
    - containerPort: 8080
    - containerPort: 8081
    env:
    - name: REAPER_STORAGE_TYPE
      value: memory
    - name: REAPER_ENABLE_DYNAMIC_SEED_LIST
      value: "false"
    - name: REAPER_DATACENTER_AVAILABILITY
      value: ALL
    - name: REAPER_HEAP_SIZE
      value: "2147483648"
    - name: REAPER_HTTP_MANAGEMENT_ENABLE
      value: "true"
    - name: REAPER_AUTH_ENABLED
      value: "false"
    command: ["java"]
    args:
    - "-DREAPER_ENCRYPTION_KEY=my-secret-encryption-key-32chars!!!"
    - "-Xms2147483648"
    - "-Xmx2147483648"
    - "-jar"
    - "/usr/local/bin/cassandra-reaper.jar"
    - "server"
    - "/etc/cassandra-reaper/config/cassandra-reaper.yml"
    volumeMounts:
    - name: config
      mountPath: /etc/cassandra-reaper/config
    resources:
      limits:
        memory: 3Gi
      requests:
        cpu: 100m
        memory: 256Mi
  volumes:
  - name: config
    configMap:
      name: reaper-config
  - name: config-dir
    emptyDir: {}