apiVersion: v1
kind: Namespace
metadata:
  name: "${NAMESPACE}"
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-auth
  namespace: "${NAMESPACE}"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "${DOCKERCONFIGJSON}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: "${NAMESPACE}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: storage-volume
          mountPath: "/var/lib/registry"
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: registry-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: "${NAMESPACE}"
spec:
  accessModes:
    - ReadWriteOnce # Suitable for a single node; use ReadWriteMany for multi-node NFS
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-client-retain
---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: "${NAMESPACE}"
spec:
  selector:
    app: registry
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer
  loadBalancerIP: "${ADDRESS}"