apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-connect-logs-pvc
  namespace: kafka
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-connect
  namespace: kafka
  annotations:
    strimzi.io/use-connector-resources: "true" # Enables management of connectors via KafkaConnector CR
spec:
  version: 3.9.0 # Match your Kafka version
  replicas: 1 # Adjust as needed
  bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc:29092 # Points to your Kafka cluster's external listener
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-offsets
    config.storage.topic: connect-configs
    status.storage.topic: connect-status
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
    config.storage.replication.factor: 3
    offset.storage.replication.factor: 3
    status.storage.replication.factor: 3
    plugin.path: /opt/kafka/plugins
  logging:
    type: inline
    loggers:
      log4j.rootLogger: "WARN, stdout"
      log4j.appender.stdout: "org.apache.log4j.ConsoleAppender"
      log4j.appender.stdout.layout: "org.apache.log4j.PatternLayout"
      log4j.appender.stdout.layout.ConversionPattern: "[%d] %p %m (%c)%n"
  resources:
    requests:
      memory: "500Mi"
      cpu: "0.5"
    limits:
      memory: "1Gi"
      cpu: "1"
  jvmOptions:
    -Xms: 256m
    -Xmx: 1024m
  template:
    pod:
      imagePullSecrets:
        - name: registry-auth  # Add this to allow pulling the image
      securityContext:
        runAsUser: 0  # Run as root
        fsGroup: 0    # Ensure filesystem access
      volumes:
        - name: kafka-connect-logs
          persistentVolumeClaim:
            claimName: kafka-connect-logs-pvc
  build: # Optional: Add JDBC connector plugin for Oracle (or other connectors)
    output:
      type: docker
      image: 192.168.64.106:5000/my-oracle-connect:3.9.0
      pushSecret: registry-auth  # Reference the new docker-registry secret
    plugins:
      - name: jdbc-connector
        artifacts:
          - type: jar
            url: https://packages.confluent.io/maven/io/confluent/kafka-connect-jdbc/10.7.15/kafka-connect-jdbc-10.7.15.jar
            fileName: kafka-connect-jdbc.jar
          - type: jar
            url: https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc8/23.2.0.0/ojdbc8-23.2.0.0.jar
            fileName: ojdbc8.jar