apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kafka-connect-secret-reader
  namespace: kafka
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kafka-connect-secret-reader-binding
  namespace: kafka
subjects:
  - kind: ServiceAccount
    name: my-connect-connect
    namespace: kafka
roleRef:
  kind: Role
  name: kafka-connect-secret-reader
  apiGroup: rbac.authorization.k8s.io