apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: test-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.64.100-192.168.64.150

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: test-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - test-pool
