apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-pvc
  namespace: oracle
spec:
  accessModes:
    - ReadWriteOnce  # NFS typically supports ReadWriteOnce; use ReadWriteMany if needed
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-storage-retain
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-db
  namespace: oracle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle
  template:
    metadata:
      labels:
        app: oracle
    spec:
      imagePullSecrets:
      - name: registry-auth  # Reference the Secret here
      containers:
      - name: oracle
        image: 192.168.64.106:5000/oracle-xe:21.3.0
        #image: container-registry.oracle.com/database/enterprise:latest  # Official Oracle image (requires login)
        ports:
        - containerPort: 1521  # Oracle listener port
        - containerPort: 5500  # Enterprise Manager port
        env:
        - name: ORACLE_SID
          value: "ORCL"
        - name: ORACLE_PDB
          value: "ORCLPDB"
        - name: ORACLE_PWD
          value: "YourSecurePassword123"  # Replace with a secure password
        volumeMounts:
        - name: oracle-storage
          mountPath: "/opt/oracle/oradata"  # Default data directory for Oracle
      volumes:
      - name: oracle-storage
        persistentVolumeClaim:
          claimName: oracle-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-service
  namespace: oracle
  annotations:
    metallb.universe.tf/address-pool: fixed-pool
    metallb.universe.tf/loadBalancerIP: "192.168.64.107"
spec:
  selector:
    app: oracle
  ports:
  - name: listener
    protocol: TCP
    port: 1521
    targetPort: 1521
  - name: em
    protocol: TCP
    port: 5500
    targetPort: 5500
  type: LoadBalancer