apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: registry
  annotations:
    metallb.universe.tf/address-pool: fixed-pool
    metallb.universe.tf/loadBalancerIP: "192.168.64.106"  # Fixed IP via annotation
spec:
  selector:
    app: registry
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer