apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-test-pvc
spec:
  storageClassName: nfs-storage-delete
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
