apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.9.0
    replicas: 3
    listeners:
      - name: internal
        port: 29092
        type: internal
        tls: false
      - name: external
        port: 9092
        type: loadbalancer
        tls: false
        configuration:
          bootstrap:
            loadBalancerIP: "192.168.64.100" # Fixed IP for bootstrap
    config:
      log.retention.hours: 168
      log.retention.bytes: 838860800
      auto.create.topics.enable: true
      inter.broker.listener.name: "internal"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
      class: nfs-client-retain
    resources:
      requests:
        memory: "500Mi"
        cpu: "0.5"
      limits:
        memory: "1Gi"
        cpu: "1"
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
      class: nfs-client-retain
    resources:
      requests:
        memory: "500Mi"
        cpu: "0.5"
      limits:
        memory: "1Gi"
        cpu: "1"
  entityOperator:
    topicOperator: {}
    userOperator: {}
