apiVersion: v1
kind: Service
metadata:
  name: my-connect-connect-api-lb
  namespace: kafka
spec:
  type: LoadBalancer
  loadBalancerIP: "192.168.64.107"
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
  selector:
    strimzi.io/cluster: my-connect
    strimzi.io/kind: KafkaConnect