apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: wefox-oracle-jdbc-source
  namespace: kafka
  labels:
    strimzi.io/cluster: my-connect
spec:
  class: io.confluent.connect.jdbc.JdbcSourceConnector
  tasksMax: 1
  config:
    connection.url: "jdbc:oracle:thin:@//192.168.64.1:1521/FREEPDB1"
    connection.user: "wefox"
    connection.password: "${secrets:kafka/oracle-credentials:password_wefox}"
    mode: "incrementing"
    incrementing.column.name: "LEGACY_ID"
    table.whitelist: "REPORT_SENDS"
    topic.prefix: "ORA_TABLE_"
    poll.interval.ms: "5000"
    schema.pattern: "WEFOX"
    numeric.mapping: "best_fit"
    driver.class: "oracle.jdbc.OracleDriver"
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: io.apicurio.registry.utils.converter.ExtJsonConverter
    value.converter.apicurio.registry.url: "http://192.168.64.103:8282/apis/registry/v2"
    value.converter.apicurio.registry.converter.serializer: io.apicurio.registry.utils.serde.JsonSchemaKafkaSerializer
    value.converter.apicurio.registry.converter.deserializer: io.apicurio.registry.utils.serde.JsonSchemaKafkaDeserializer
    value.converter.apicurio.registry.artifact-resolver-strategy: io.apicurio.registry.serde.strategy.TopicIdStrategy
    value.converter.apicurio.registry.auto-register: true
    value.converter.apicurio.registry.use-latest-version: true
    value.converter.apicurio.registry.max-schemas-per-subject: 1000
    topic.creation.enable: true
    topic.creation.default.partitions: 1
    topic.creation.default.replication.factor: 3